### ISSUE TITLE
Quote List

### ISSUE THREAD

**Issue by MegaMasterX** [MegaMasterX/ColonelBot#4]
Replacement for Nitori's Quote System. This feature should support:
- Quote adding
- Quote editing based on submitting user ID
- Quote removal and reorganizing the quote list to avoid blank "deleted" entries

**Comment by MegaMasterX** [comment]
First iteration completed. A few bugs are remaining in that the lists for Author and Quote are mismatched after use and a user can change their Discord Name to delete someone elses' quotes without authorization.

**Comment by Prof9** [comment]
hehehehe

**Comment by MegaMasterX** [comment]
Quote system disabled as Nitori is operational again.
